GET localhost:8080/api/order
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ijl6YUw3M0ZhZlprLWRWTDZsSXFlRCJ9.eyJpc3MiOiJodHRwczovL2Rldi1qbTJ3ZmRpYWJpejV6dWdrLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJNc0I2a25GRXd6aWJMT0JxYUxwTDdCYkVqdTExaHp3a0BjbGllbnRzIiwiYXVkIjoibG9jYWxob3N0OjgwODAvYXBpIiwiaWF0IjoxNzAwMTYzNDY3LCJleHAiOjE3MDAyNDk4NjcsImF6cCI6Ik1zQjZrbkZFd3ppYkxPQnFhTHBMN0JiRWp1MTFoendrIiwiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIn0.NpCJgxM4TDRJZQexg6l_NH0PWprr2ePzJMpVX3DGoOlh0fyXI7EED1czyCE_h2ffcG7m8rRLZZ4-hhnWjRA2DxbA3fDKStKnQxEA7OIfO3E6VuCvr-OxiTtJYLw4Hg2LzFjk5ZZ1iJ-t0_U2vC9x3yhXUKBWf_yoH2Jug-CSZHczB3skmYgn8f1vs0Do183BBuxJYyu2xMi6qzyHwQKfipAdcx7frDaIzcSth4D3ZpCJ_9bzcG7ETHPVITT_xTv8uI2CVr7ls48Oz02KLQMRbJQ3fsaL8kyLs4O7EsTWxo6FQmPfwKOlc7Onougso6LyE7259GA7Pa2rbyAiongn4Q